---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  - echo "some checks passed"

notifications:
  slack: devops-team-otus:Wv8bMwwnJCwJhuIxP62nzipf
